[package]
name = "storescp"
version = "0.8.1"
authors = ["Victor Saase <vsaase@gmail.com>", "Eduardo Pinho <enet4mikeenet@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
description = "A server accepting DICOM C-STORE"
categories = ["command-line-utilities"]
keywords = ["dicom", "store"]
readme = "README.md"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
dicom-core = { git = "https://github.com/momostarsky/dicom-rs.git", tag = "v0.8.2" }
dicom-ul = {  git = "https://github.com/momostarsky/dicom-rs.git", tag = "v0.8.2", features = ["async"] }
dicom-object = {  git = "https://github.com/momostarsky/dicom-rs.git", tag = "v0.8.2" }
dicom-encoding = { git = "https://github.com/momostarsky/dicom-rs.git", tag = "v0.8.2" }
dicom-dictionary-std = { git = "https://github.com/momostarsky/dicom-rs.git", tag = "v0.8.2" }
dicom-transfer-syntax-registry = { git = "https://github.com/momostarsky/dicom-rs.git", tag = "v0.8.2" }

tracing = "0.1.36"
tracing-subscriber = "0.3.19"
tokio = { version = "1.47.1", features = ["full"] }

rdkafka = "0.34"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "mysql"] }
common = { path = "../common" }
serde_json = "1.0.142"
config = "0.13"  # 配置文件解析
dotenv = "0.15"  # 加载 .env 文件
futures = "0.3.31"
futures-util = "0.3.31"
