[package]
name = "wado-server"
version = "0.1.0"
edition = "2024"
[profile.release]
lto = true
opt-level = "s"
[dependencies]
dicom-core = { version = "0.8.2" }
dicom-ul = { version = "0.8.2", features = ["async"] }
dicom-object = { version = "0.8.2" }
dicom-encoding = { version = "0.8.2" }
dicom-dictionary-std = { version = "0.8.1" }
dicom-transfer-syntax-registry = { version = "0.8.2" }
dicom-pixeldata = { version = "0.8.2", features = ["gdcm", "rayon", "image", "rle", "jpeg"] }
actix-web = "4.11.0"
actix-cors = "0.7.1"
slog = "2.7.0"
slog-term = "2.9.2"
slog-async = "2.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_qs = "0.12"
serde_json = "1.0.145"
urlencoding = "2.1.3"
common = { path = "../common" }
futures-util = "0.3.31"
axum = "0.7.9"
tokio = { version = "1.47.1", features = ["full"] }
http = "0.2.12"
http-body-util = "0.1"
futures = "0.3.31"
mime = "0.3.17"
uuid = { version = "1.18.1", features = ["v4", "v7"] }
chrono = "0.4.42"
redis = { version = "0.27.6", features = ["tokio-comp"] }
url = "2.5.7"
gdcm_conv = "0.1.7"
reqwest = { version = "0.11.27", features = ["json"] }
openssl = "0.10.73"