[package]
name = "wado-server"
version = "0.1.0"
edition = "2024"

[dependencies]

dicom-core = { workspace = true }
dicom-ul = { workspace = true }
dicom-object = { workspace = true }
dicom-encoding = { workspace = true }
dicom-dictionary-std = { workspace = true }
dicom-transfer-syntax-registry = { workspace = true }
dicom-pixeldata = { workspace = true }
actix-web = { workspace = true }
actix-cors = { workspace = true }
slog = { workspace = true }
slog-term = { workspace = true }
slog-async = { workspace = true }
serde = { workspace = true }
serde_qs = { workspace = true }
serde_json = { workspace = true }
urlencoding = { workspace = true }
futures-util = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
futures = { workspace = true }
mime = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
redis = { workspace = true }
url = { workspace = true }
gdcm_conv = { workspace = true }
reqwest = { workspace = true }
openssl = { workspace = true }
database = { path = "../database" }
common = { path = "../common" }
