[package]
name = "wado-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-cors = "0.7.0"
slog = "2.7.0"
slog-term = "2.9.1"
slog-async = "2.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_qs = "0.12"
serde_json = "1.0.141"
urlencoding = "2.1.3"

http = "0.2.12"  # 加载 .env 文件
common = { path = "../common" }
