[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
config = "0.13"  # 配置文件解析
dotenv = "0.15"
clap = { version = "4.5.43", features = ["derive"] }
dicom-core = {  version = "0.8.2" }
dicom-ul = {  version = "0.8.2", features = ["async"] }
dicom-object = {   version = "0.8.2" }
dicom-encoding = {  version = "0.8.2" }
dicom-dictionary-std = {   version = "0.8.1" }
dicom-transfer-syntax-registry = {   version = "0.8.2" }
async-trait = "0.1"
sqlx = { version = "0.7.4", features = ["mysql", "runtime-tokio-native-tls"] }
tracing = "0.1.41"
tokio = { version = "1.47.1", features = ["full"] }
urlencoding = "2.1.3"
url = "2.4"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "local-time"] }
tracing-appender = "0.2"