[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.142"
serde = { version = "1.0.219", features = ["derive"] }
config = "0.13"  # 配置文件解析
dotenv = "0.15"
clap = { version = "4.5.43", features = ["derive"] }
dicom-core = { version = "0.8.2" }
dicom-ul = { version = "0.8.2", features = ["async"] }
dicom-object = { version = "0.8.2" }
dicom-encoding = { version = "0.8.2" }
dicom-dictionary-std = { version = "0.8.1" }
dicom-transfer-syntax-registry = { version = "0.8.2" }
dicom-pixeldata = { version = "0.8.2", features = ["gdcm","rayon","image","rle","jpeg"] }
async-trait = "0.1"
sqlx = { version = "0.8.6", features = ["mysql", "chrono",
    "runtime-tokio",
    "mysql",
    "macros",

    "runtime-tokio-native-tls"] }
tracing = "0.1.41"
tokio = { version = "1.47.1", features = ["full"] }
urlencoding = "2.1.3"
url = "2.4"
slog = "2.7.0"
slog-term = "2.9.1"
slog-async = "2.8.0"
slog-stdlog = "4.1.1"
slog-scope = "4.1.1"
rdkafka = "0.34"
futures = "0.3.31"
futures-util = "0.3.31"
chrono = { version = "0.4", features = ["serde"] }
rayon = "1.10.0"
thiserror = "2.0.12"
encoding_rs = "0.8.35"
gdcm_conv = "0.1.7"
rstest = { version = "0.26.1"  }
openssl = { version = "0.10", features = ["v102", "vendored"] }  # 自带 OpenSSL，无需额外安装
x509-parser = "0.13"  # 请检查最新版本
der = "0.7"
pem = "1.0"
hex = "0.4.3"        # x509-parser 可能依赖它
regex = "1.11.1"
lazy_static = "1.5.0"